---
resources:
  - name: ghr
    type: github-release
    source:
      owner: cappyzawa
      repository: fly-lint.vim
      access_token: ((github-access-token))
  - name: semver
    type: semver
    source:
      driver: git
      uri: git@github.com:cappyzawa/fly-lint.vim.git
      branch: master
      private_key: ((private-key))
      commit_message: "[ci skip] bump version"
      file: VERSION
  - name: repo
    type: git
    source:
      uri: https://github.com/cappyzawa/fly-lint.vim
      branch: master

jobs:
  - name: bump
    build_logs_to_retain: 20
    plan:
      - get: repo
        trigger: true
      - put: semver
        params:
          bump: patch
  - name: release
    build_logs_to_retain: 20
    plan:
      - get: semver
        passed:
          - bump
        trigger: true
      - put: ghr
        params:
          name: semver/version
          tag: semver/version
          tag_prefix: v
